---
name: Deploy 

on:
  push:
    branches:
        - main
        - master
        - develop
        - staging



jobs:
    vars:
        uses: OrangeLiberia/pipelines/.github/workflows/vars.yml@main
    deploy:
        needs: vars
        uses: OrangeLiberia/pipelines/.github/workflows/deploy.yml@main
    postgresql:
        needs: vars
        uses: OrangeLiberia/pipelines/.github/workflows/postgresql.yml@main
    redis:
        needs: vars
        uses: OrangeLiberia/pipelines/.github/workflows/redis.yml@main
